"""
pipeline/email_client.py — Email Alert Notifier
Sends alert summary emails via SMTP (Gmail App Password recommended).
Falls back to console logging if SMTP credentials are not set.
"""
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

from config.settings import (
    ALERT_EMAIL_TO, SMTP_HOST, SMTP_PORT,
    SMTP_USER, SMTP_PASSWORD, EMAIL_ENABLED,
)


def send_alert_email(
    alert: dict,
    ticket: dict,
    root_cause_summary: str,
    suggested_fix: str,
    confidence_score: float,
    time_saved_minutes: float,
) -> dict:
    """
    Send an alert summary email.
    Returns: {sent: bool, mocked: bool, to: str}
    """
    affected  = alert.get("affected_service", "unknown")
    severity  = alert.get("severity", "HIGH")
    ticket_id = ticket.get("ticket_id", "N/A")
    now       = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    subject = f"[TriagePulseAI] {severity} Alert — {affected} ({ticket_id})"

    html_body = f"""
    <html><body style="font-family: Arial, sans-serif; background:#f4f4f4; padding:20px;">
      <div style="max-width:640px; margin:auto; background:#fff; border-radius:8px;
                  border-left:6px solid {'#c0392b' if severity in ('HIGH','CRITICAL') else '#e67e22'};
                  padding:24px; box-shadow:0 2px 8px rgba(0,0,0,0.1);">

        <h2 style="margin:0 0 4px 0; color:#c0392b;">
          TriagePulseAI — Incident Alert
        </h2>
        <p style="color:#888; margin:0 0 20px 0; font-size:13px;">{now}</p>

        <table style="width:100%; border-collapse:collapse; margin-bottom:20px;">
          <tr><td style="padding:6px 0; color:#555; width:40%"><b>Service</b></td>
              <td style="padding:6px 0; color:#222">{affected}</td></tr>
          <tr><td style="padding:6px 0; color:#555"><b>Severity</b></td>
              <td style="padding:6px 0; color:#c0392b"><b>{severity}</b></td></tr>
          <tr><td style="padding:6px 0; color:#555"><b>Error</b></td>
              <td style="padding:6px 0; color:#222; font-size:12px; font-family:monospace">
                {alert.get('error_signature', 'N/A')}</td></tr>
          <tr><td style="padding:6px 0; color:#555"><b>Jira Ticket</b></td>
              <td style="padding:6px 0; color:#2980b9">{ticket_id}</td></tr>
          <tr><td style="padding:6px 0; color:#555"><b>AI Confidence</b></td>
              <td style="padding:6px 0; color:#27ae60"><b>{confidence_score:.0%}</b></td></tr>
          <tr><td style="padding:6px 0; color:#555"><b>Time Saved</b></td>
              <td style="padding:6px 0; color:#27ae60">~{time_saved_minutes:.0f} minutes</td></tr>
        </table>

        <div style="background:#f8f9fa; border-radius:6px; padding:16px; margin-bottom:16px;">
          <h3 style="margin:0 0 8px 0; color:#333;">Root Cause (AI Analysis)</h3>
          <p style="margin:0; color:#555; line-height:1.6;">{root_cause_summary}</p>
        </div>

        <div style="background:#eafaf1; border-radius:6px; padding:16px; margin-bottom:16px;">
          <h3 style="margin:0 0 8px 0; color:#27ae60;">Suggested Fix</h3>
          <p style="margin:0; color:#555; line-height:1.6; white-space:pre-line;">{suggested_fix}</p>
        </div>

        <div style="background:#fef9e7; border-radius:6px; padding:16px;">
          <h3 style="margin:0 0 8px 0; color:#f39c12;">Alert Description</h3>
          <p style="margin:0; color:#555; line-height:1.6;">{alert.get('description', 'N/A')}</p>
        </div>

        <p style="margin-top:24px; color:#aaa; font-size:11px; text-align:center;">
          Auto-generated by TriagePulseAI &bull; Do not reply to this email
        </p>
      </div>
    </body></html>
    """

    if not EMAIL_ENABLED:
        print("[email] SMTP not configured — printing alert to console:")
        print(f"  TO:      {ALERT_EMAIL_TO}")
        print(f"  SUBJECT: {subject}")
        print(f"  BODY:    {root_cause_summary[:120]}...")
        return {"sent": False, "mocked": True, "to": ALERT_EMAIL_TO}

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = SMTP_USER
        msg["To"]      = ALERT_EMAIL_TO
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, ALERT_EMAIL_TO, msg.as_string())

        print(f"[email] Alert email sent to {ALERT_EMAIL_TO}")
        return {"sent": True, "mocked": False, "to": ALERT_EMAIL_TO}

    except Exception as err:
        print(f"[email] Failed to send email: {err}")
        return {"sent": False, "mocked": True, "to": ALERT_EMAIL_TO, "error": str(err)}
